//! Generates `.github/workflows/cargo-unikernel.yml`: `cargo unikernel github init` takes
//! a project from "has cargo-unikernel.toml" to "publishes a built image on every tag push".
//!
//! The kernel download+compile is the most expensive step in the pipeline, so the generated
//! workflow caches both the tool's own cargo install and `~/.cache/cargo-unikernel` across
//! runs — without it, every CI run would redo the full kernel build from scratch.

use anyhow::{Context, Result, bail};
use std::path::{Path, PathBuf};

/// Writes `.github/workflows/cargo-unikernel.yml`, wired to build with `--config config_path`
/// on every tag push (and on pushes to `main`, to keep the kernel-build cache warm).
///
/// # Errors
///
/// Returns an error if `.github/workflows/cargo-unikernel.yml` already exists, or if creating
/// the directory/writing the file fails.
pub fn init(config_path: &Path, attest_provenance: bool) -> Result<()> {
    let workflows_dir = PathBuf::from(".github/workflows");
    std::fs::create_dir_all(&workflows_dir)
        .with_context(|| format!("failed to create {}", workflows_dir.display()))?;

    let out_path = workflows_dir.join("cargo-unikernel.yml");
    if out_path.exists() {
        bail!(
            "{} already exists — remove it first if you want to regenerate it",
            out_path.display()
        );
    }

    let config_arg = config_path.display();
    // If the config can be loaded and pins `project.cargo_unikernel_version` (required for
    // sev-snp, optional for casual — see `schema::ValidationError::SevSnpRequiresPinnedCliVersion`),
    // install that exact version instead of whatever's newest on crates.io: CI should build
    // with the same CLI version the config was written against, not silently drift onto a
    // newer one with a different pinned kernel/Dockerfile. `Config::validate` still catches a
    // mismatch (e.g. a stale cache) as a build-time failure either way.
    let pinned_version = crate::config::load(config_path)
        .ok()
        .and_then(|c| c.project.cargo_unikernel_version);
    let install_cmd = pinned_version.as_deref().map_or_else(
        || "cargo install cargo-unikernel --locked".to_string(),
        |v| format!("cargo install cargo-unikernel --version {v} --locked"),
    );
    // `id-token: write` mints a short-lived OIDC token to sign via Sigstore; `attestations:
    // write` publishes it to GitHub's attestation store. Both additive to `contents: write`,
    // and only requested when `attest_provenance` opts in — a real widening of what the
    // workflow can do, so never assumed by default.
    let permissions = if attest_provenance {
        "    permissions:\n      contents: write\n      id-token: write\n      attestations: write\n"
    } else {
        "    permissions:\n      contents: write\n"
    };
    // Verifiable via `gh attestation verify <file> --repo <owner>/<repo>` — proof that this
    // exact workflow run, from this exact commit, produced these exact bytes.
    // Only the actual release publish should happen for a real tag, not the cache-warming
    // builds below.
    let tag_only = "if: startsWith(github.ref, 'refs/tags/')\n        ";
    let attestation_step = if attest_provenance {
        format!(
            "\n      - name: Attest build provenance\n        {tag_only}uses: actions/attest-build-provenance@v4\n        with:\n          subject-path: dist/*\n"
        )
    } else {
        String::new()
    };
    let workflow = format!(
        r#"# Generated by `cargo unikernel github init`. Publishes a unikernel image as a
# GitHub Release asset on every tag push matching `v*`, using this project's
# {config_arg}. Also builds (but doesn't publish) on every push to `main`: GitHub Actions
# cache scopes are isolated per tag — a cache from one release tag is never reachable from
# another — so the only way a tag-triggered build can inherit a warm cache at all is via the
# repository's default-branch cache, which this keeps populated. See "Restrictions for
# accessing a cache" in GitHub's dependency-caching docs. Re-run `cargo unikernel github
# init` after deleting this file to regenerate it if you upgrade cargo-unikernel and want
# the latest template. Adjust `branches: [main]` below if your default branch differs.
name: cargo-unikernel release

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
{permissions}    steps:
      - uses: actions/checkout@v7

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      # Caches `cargo install cargo-unikernel` itself (the tool's own crates.io deps).
      # `.crates.toml`/`.crates2.json` (cargo's own install-tracking metadata) must be cached
      # alongside the `bin/` binary they describe — with only the binary cached, cargo finds an
      # untracked file already sitting at the destination path on a cache hit and refuses to
      # overwrite it (`error: binary ... already exists in destination`). With both cached,
      # cargo recognizes its own prior install and no-ops (unchanged) or upgrades in place (new
      # version published) without needing `--force`.
      - name: Cache cargo install
        uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
          key: ${{{{ runner.os }}}}-cargo-install-cargo-unikernel
          restore-keys: |
            ${{{{ runner.os }}}}-cargo-install-

      # Caches the build pipeline's own state: the downloaded kernel source tarball, the
      # fingerprinted bzImage cache (skips reconfigure+recompile entirely when nothing
      # kernel-config-relevant changed), ccache's object cache, and the guest/app cargo
      # registry+target dirs used inside the build container. This is what actually avoids
      # re-downloading/recompiling the kernel on every run — keyed on this project's config
      # so a hardening/kernel-version change invalidates it, with a broader restore-key
      # fallback so ccache/cargo-registry contents still get reused even then.
      - name: Cache cargo-unikernel build state (kernel source, ccache, cargo registry)
        uses: actions/cache@v6
        with:
          path: ~/.cache/cargo-unikernel
          key: ${{{{ runner.os }}}}-cargo-unikernel-${{{{ hashFiles('{config_arg}') }}}}
          restore-keys: |
            ${{{{ runner.os }}}}-cargo-unikernel-

      - name: Install cargo-unikernel
        run: {install_cmd}

      - name: Build image
        run: cargo unikernel build --config {config_arg}

      # `--no-build`: this run already built the image above (needed on every trigger, to
      # keep the cache warm) — rebuilding here would just redo the same work.
      - name: Publish release
        {tag_only}env:
          GH_TOKEN: ${{{{ github.token }}}}
        run: cargo unikernel release --config {config_arg} --tag "${{{{ github.ref_name }}}}" --no-build
{attestation_step}"#,
    );

    std::fs::write(&out_path, workflow)
        .with_context(|| format!("failed to write {}", out_path.display()))?;
    println!("Wrote {}", out_path.display());
    println!(
        "Push a tag matching v*.*.* to trigger a build + GitHub Release (pushes to `main` \
         also build, to keep the cache warm — see the comment at the top of the workflow file)."
    );
    if attest_provenance {
        println!(
            "Build-provenance attestation enabled — verify a downloaded asset with \
             `gh attestation verify <file> --repo <owner>/<repo>`."
        );
    }
    if let Some(v) = &pinned_version {
        println!(
            "{config_arg} pins cargo_unikernel_version = \"{v}\" — the workflow installs that \
             exact version, and `cargo unikernel build` fails closed if a different one ever \
             runs against it instead."
        );
    } else {
        println!(
            "{config_arg} doesn't pin `project.cargo_unikernel_version`, so the workflow \
             installs whatever's newest on crates.io — pin it (required for sev-snp) and \
             re-run `github init` after deleting this file to have CI install that exact \
             version instead."
        );
    }
    Ok(())
}

#[cfg(test)]
// Tests panicking (via unwrap/expect/assert) on failure is the point, not a code
// smell — this is the standard justified exception to these lints.
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
mod tests {
    use super::*;

    /// `init()` writes relative to the *process* cwd (`.github/workflows/...`), not a path
    /// parameter — these tests must serialize on and restore the cwd, since `cargo test`
    /// runs them on multiple threads within one process.
    static CWD_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

    fn in_temp_dir<T>(f: impl FnOnce(&Path) -> T) -> T {
        let _guard = CWD_LOCK.lock().unwrap();
        let dir = std::env::temp_dir().join(format!("cu-github-test-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let original = std::env::current_dir().unwrap();
        std::env::set_current_dir(&dir).unwrap();
        let result = f(&dir);
        std::env::set_current_dir(original).unwrap();
        std::fs::remove_dir_all(&dir).ok();
        result
    }

    #[test]
    fn writes_workflow_referencing_given_config_path() {
        in_temp_dir(|_dir| {
            init(Path::new("my-custom-config.toml"), false).unwrap();
            let workflow =
                std::fs::read_to_string(".github/workflows/cargo-unikernel.yml").unwrap();
            assert!(workflow.contains("my-custom-config.toml"));
            assert!(workflow.contains("cargo unikernel release --config my-custom-config.toml"));
            assert!(workflow.contains("tags:"));
        });
    }

    #[test]
    fn cargo_install_cache_includes_the_install_tracking_metadata() {
        // Caching ~/.cargo/bin alone isn't enough: without .crates.toml/.crates2.json (cargo's
        // record of what it installed there), a cache hit leaves an untracked binary sitting at
        // the destination path, and `cargo install` refuses to overwrite it without --force.
        in_temp_dir(|_dir| {
            init(Path::new("cargo-unikernel.toml"), false).unwrap();
            let workflow =
                std::fs::read_to_string(".github/workflows/cargo-unikernel.yml").unwrap();
            assert!(workflow.contains("~/.cargo/bin"));
            assert!(workflow.contains("~/.cargo/.crates.toml"));
            assert!(workflow.contains("~/.cargo/.crates2.json"));
            assert!(!workflow.contains("cargo install cargo-unikernel --locked --force"));
        });
    }

    #[test]
    fn pins_ci_install_to_the_configs_cargo_unikernel_version_when_set() {
        in_temp_dir(|_dir| {
            std::fs::write(
                "cargo-unikernel.toml",
                crate::config::scaffold::pin_tool_version(include_str!(
                    "../examples/cargo-unikernel.sev-snp.toml"
                )),
            )
            .unwrap();
            init(Path::new("cargo-unikernel.toml"), false).unwrap();
            let workflow =
                std::fs::read_to_string(".github/workflows/cargo-unikernel.yml").unwrap();
            let expected = format!(
                "cargo install cargo-unikernel --version {} --locked",
                crate::schema::CLI_VERSION
            );
            assert!(workflow.contains(&expected));
            assert!(!workflow.contains("cargo install cargo-unikernel --locked\n"));
        });
    }

    #[test]
    fn falls_back_to_unpinned_install_when_config_missing_or_unpinned() {
        in_temp_dir(|_dir| {
            // No config file written at all — `github init` doesn't require one to exist.
            init(Path::new("cargo-unikernel.toml"), false).unwrap();
            let workflow =
                std::fs::read_to_string(".github/workflows/cargo-unikernel.yml").unwrap();
            assert!(workflow.contains("cargo install cargo-unikernel --locked\n"));
            assert!(!workflow.contains("--version"));
        });
    }

    #[test]
    fn refuses_to_overwrite_existing_workflow() {
        in_temp_dir(|_dir| {
            init(Path::new("cargo-unikernel.toml"), false).unwrap();
            let err = init(Path::new("cargo-unikernel.toml"), false).unwrap_err();
            assert!(err.to_string().contains("already exists"));
        });
    }

    #[test]
    fn attestation_step_and_permissions_omitted_by_default() {
        in_temp_dir(|_dir| {
            init(Path::new("cargo-unikernel.toml"), false).unwrap();
            let workflow =
                std::fs::read_to_string(".github/workflows/cargo-unikernel.yml").unwrap();
            assert!(!workflow.contains("attest-build-provenance"));
            assert!(!workflow.contains("id-token: write"));
            assert!(!workflow.contains("attestations: write"));
            // The base permission the release step always needs must still be present.
            assert!(workflow.contains("contents: write"));
        });
    }

    #[test]
    fn attest_provenance_adds_step_and_required_permissions() {
        in_temp_dir(|_dir| {
            init(Path::new("cargo-unikernel.toml"), true).unwrap();
            let workflow =
                std::fs::read_to_string(".github/workflows/cargo-unikernel.yml").unwrap();
            assert!(workflow.contains("uses: actions/attest-build-provenance@v4"));
            assert!(workflow.contains("subject-path: dist/*"));
            assert!(workflow.contains("id-token: write"));
            assert!(workflow.contains("attestations: write"));
            assert!(workflow.contains("contents: write"));
            // The attestation step must come after the build step, since it attests the
            // files that step just produced.
            let build_pos = workflow.find("Build image").unwrap();
            let attest_pos = workflow.find("Attest build provenance").unwrap();
            assert!(build_pos < attest_pos);
            // And it must only run for an actual release, same as the publish step.
            assert!(workflow.contains(
                "- name: Attest build provenance\n        if: startsWith(github.ref, 'refs/tags/')"
            ));
        });
    }

    #[test]
    fn also_triggers_on_push_to_main_to_keep_the_default_branch_cache_warm() {
        // GitHub Actions cache scopes are isolated per tag (a cache from one release tag is
        // never reachable from another), so a tag-triggered build can only ever inherit a
        // warm cache via the repository's default-branch cache — which requires something to
        // actually populate it. See "Restrictions for accessing a cache" in GitHub's
        // dependency-caching docs.
        in_temp_dir(|_dir| {
            init(Path::new("cargo-unikernel.toml"), false).unwrap();
            let workflow =
                std::fs::read_to_string(".github/workflows/cargo-unikernel.yml").unwrap();
            assert!(workflow.contains("branches:\n      - main"));
        });
    }

    #[test]
    fn build_step_always_runs_but_publish_step_is_tag_only_and_skips_rebuilding() {
        in_temp_dir(|_dir| {
            init(Path::new("cargo-unikernel.toml"), false).unwrap();
            let workflow =
                std::fs::read_to_string(".github/workflows/cargo-unikernel.yml").unwrap();
            assert!(workflow.contains("- name: Build image"));
            assert!(workflow.contains("run: cargo unikernel build --config cargo-unikernel.toml"));
            assert!(!workflow.contains("- name: Build image\n        if:"));
            assert!(workflow.contains(
                "- name: Publish release\n        if: startsWith(github.ref, 'refs/tags/')"
            ));
            assert!(workflow.contains("--no-build"));
            let build_pos = workflow.find("Build image").unwrap();
            let publish_pos = workflow.find("Publish release").unwrap();
            assert!(build_pos < publish_pos);
        });
    }
}
