[package]
name = "cargo-unikernel-init"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Minimal guest PID-1 embedded into cargo-unikernel images."
readme = "README.md"
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "cargo-unikernel-init"
path = "src/main.rs"

[features]
default = []
sev-snp = []
net-ipv4 = ["cargo-unikernel-common/net-ipv4"]
net-ipv6 = ["cargo-unikernel-common/net-ipv6"]
hardening-net-spoofing = ["cargo-unikernel-common/hardening-net-spoofing"]
hardening-icmp = ["cargo-unikernel-common/hardening-icmp"]
hardening-tcp = ["cargo-unikernel-common/hardening-tcp"]
hardening-info-leak = ["cargo-unikernel-common/hardening-info-leak"]
hardening-ptrace-bpf = ["cargo-unikernel-common/hardening-ptrace-bpf"]
hardening-kexec-fs = ["cargo-unikernel-common/hardening-kexec-fs"]
danger-allow-write-execute = ["cargo-unikernel-common/danger-allow-write-execute"]
storage-persistent = ["cargo-unikernel-common/storage-persistent"]

[dependencies]
cargo-unikernel-common = { path = "../cargo-unikernel-common" }
libc = "0.2"

[lints.rust]
warnings = "deny"
future_incompatible = "deny"
unused = "deny"
missing_docs = "deny"
missing_debug_implementations = "deny"
unreachable_pub = "deny"

[lints.clippy]
all = "deny"
pedantic = "deny"
nursery = "deny"
cargo = "deny"
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
